runtime: python38

includes:
  - env_variables.yaml

handlers:
- url: /favicon\.ico
  static_files: static/icons/favicon.ico
  upload: favicon\.ico

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /static
  static_dir: static

- url: /.*
  script: auto
