runtime: python38

includes:
  - env_variables.yaml

handlers:
- url: /(robots\.txt|site\.webmanifest|browserconfig\.xml)$
  static_files: static/manifests/\1
  upload: static/manifests/.*

- url: /(favicon\.ico|favicon-\d{2}x\d{2}\.png|android-chrome-\d{3}x\d{3}\.png|apple-touch-icon\.png|mstile-150x150\.png|safari-pinned-tab\.svg|og-image\.jpg)$
  static_files: static/icons/\1
  upload: static/icons/.*

- url: /(sw\.js)$
  static_files: static/js/\1
  upload: static/js/sw\.js

- url: /css
  static_dir: static/css

- url: /fonts
  static_dir: static/fonts

- url: /icons
  static_dir: static/icons

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

# to handle /static/og-image.jpg
- url: /static
  static_dir: static/icons

- url: /.*
  script: auto
